import hashlib
import json
import os
from collections import Counter, defaultdict
from dataclasses import dataclass, field

from services.chunk_and_embed import EMBEDDING_MODEL, CodeChunk


LANGUAGE_BY_EXT = {
    ".py": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".html": "html",
    ".css": "css",
    ".scss": "scss",
    ".json": "json",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".md": "markdown",
    ".txt": "text",
    ".csv": "csv",
    ".sh": "shell",
}

GENERATED_MARKERS = (
    "@generated",
    "auto-generated",
    "autogenerated",
    "code generated",
    "generated by",
    "do not edit",
)

VENDOR_PARTS = {
    "vendor",
    "vendors",
    "third_party",
    "third-party",
}


@dataclass
class RepoFileManifest:
    file_path: str
    file_sha256: str
    size_bytes: int
    language: str | None
    extension: str
    is_generated: bool = False
    is_vendor: bool = False


@dataclass
class RepoChunkManifest:
    chunk_sha256: str
    embedding_sha256: str
    embedding_model: str
    file_path: str
    file_sha256: str
    chunk_type: str
    name: str | None
    parent_class: str | None
    start_line: int
    end_line: int
    content_bytes: int
    token_count: int | None = None


@dataclass
class RepoManifest:
    manifest_sha256: str
    files: list[RepoFileManifest] = field(default_factory=list)
    chunks: list[RepoChunkManifest] = field(default_factory=list)


def _rel_path(repo_dir: str, file_path: str) -> str:
    return os.path.relpath(file_path, repo_dir).replace(os.sep, "/")


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _looks_generated(path: str, prefix: bytes) -> bool:
    name = os.path.basename(path).lower()
    if ".generated." in name or ".gen." in name or name.endswith("_pb2.py"):
        return True
    text = prefix[:4096].decode("utf-8", errors="ignore").lower()
    return any(marker in text for marker in GENERATED_MARKERS)


def _is_vendor(rel_path: str) -> bool:
    parts = set(rel_path.split("/"))
    return bool(parts.intersection(VENDOR_PARTS))


def build_file_manifest(repo_dir: str, file_paths: list[str]) -> list[RepoFileManifest]:
    files: list[RepoFileManifest] = []
    for file_path in sorted(file_paths):
        with open(file_path, "rb") as f:
            content = f.read()
        rel_path = _rel_path(repo_dir, file_path)
        extension = os.path.splitext(file_path)[1].lower()
        files.append(RepoFileManifest(
            file_path=rel_path,
            file_sha256=_sha256_bytes(content),
            size_bytes=len(content),
            language=LANGUAGE_BY_EXT.get(extension),
            extension=extension,
            is_generated=_looks_generated(file_path, content),
            is_vendor=_is_vendor(rel_path),
        ))
    return files


def _chunk_hash(
    *,
    file_path: str,
    chunk: CodeChunk,
) -> str:
    payload = {
        "file_path": file_path,
        "chunk_type": chunk.chunk_type,
        "name": chunk.name,
        "parent_class": chunk.parent_class,
        "content": chunk.content,
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return _sha256_bytes(encoded)


def _embedding_hash(chunk: CodeChunk) -> str:
    payload = {
        "model": chunk.embedding_model,
        "text": chunk.embedding_text,
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return _sha256_bytes(encoded)


def build_chunk_manifest(
    repo_dir: str,
    chunks: list[CodeChunk],
    files: list[RepoFileManifest],
) -> list[RepoChunkManifest]:
    file_sha_by_path = {f.file_path: f.file_sha256 for f in files}
    chunk_rows: list[RepoChunkManifest] = []
    prepared: list[tuple[CodeChunk, str, str, str]] = []

    for chunk in chunks:
        rel_path = _rel_path(repo_dir, chunk.file_path)
        file_sha = file_sha_by_path.get(rel_path)
        if file_sha is None:
            continue
        chunk.embedding_path = rel_path
        chunk.embedding_model = EMBEDDING_MODEL
        base_chunk_sha = _chunk_hash(file_path=rel_path, chunk=chunk)
        chunk.embedding_sha256 = _embedding_hash(chunk)
        prepared.append((chunk, rel_path, file_sha, base_chunk_sha))

    hash_counts = Counter(base_chunk_sha for _, _, _, base_chunk_sha in prepared)
    seen_hashes: dict[str, int] = defaultdict(int)

    for chunk, rel_path, file_sha, base_chunk_sha in prepared:
        duplicate_ordinal = seen_hashes[base_chunk_sha]
        seen_hashes[base_chunk_sha] += 1
        if hash_counts[base_chunk_sha] > 1:
            chunk.chunk_sha256 = _sha256_bytes(json.dumps({
                "base_chunk_sha256": base_chunk_sha,
                "duplicate_ordinal": duplicate_ordinal,
            }, sort_keys=True, separators=(",", ":")).encode("utf-8"))
        else:
            chunk.chunk_sha256 = base_chunk_sha
        chunk_rows.append(RepoChunkManifest(
            chunk_sha256=chunk.chunk_sha256,
            embedding_sha256=chunk.embedding_sha256,
            embedding_model=chunk.embedding_model,
            file_path=rel_path,
            file_sha256=file_sha,
            chunk_type=chunk.chunk_type,
            name=chunk.name,
            parent_class=chunk.parent_class,
            start_line=chunk.start_line,
            end_line=chunk.end_line,
            content_bytes=len(chunk.content.encode("utf-8")),
            token_count=chunk.token_count,
        ))

    return sorted(
        chunk_rows,
        key=lambda c: (
            c.file_path,
            c.start_line,
            c.end_line,
            c.chunk_type,
            c.name or "",
            c.parent_class or "",
        ),
    )


def _manifest_hash(
    files: list[RepoFileManifest],
    chunks: list[RepoChunkManifest],
) -> str:
    payload = {
        "files": [
            {
                "file_path": f.file_path,
                "file_sha256": f.file_sha256,
                "size_bytes": f.size_bytes,
                "language": f.language,
                "extension": f.extension,
                "is_generated": f.is_generated,
                "is_vendor": f.is_vendor,
            }
            for f in files
        ],
        "chunks": [
            {
                "chunk_sha256": c.chunk_sha256,
                "embedding_sha256": c.embedding_sha256,
                "embedding_model": c.embedding_model,
                "file_path": c.file_path,
                "file_sha256": c.file_sha256,
                "chunk_type": c.chunk_type,
                "name": c.name,
                "parent_class": c.parent_class,
                "start_line": c.start_line,
                "end_line": c.end_line,
            }
            for c in chunks
        ],
    }
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return _sha256_bytes(encoded)


def build_repo_manifest(
    repo_dir: str,
    file_paths: list[str],
    chunks: list[CodeChunk] | None = None,
) -> RepoManifest:
    files = build_file_manifest(repo_dir, file_paths)
    chunk_rows = build_chunk_manifest(repo_dir, chunks or [], files)
    return RepoManifest(
        manifest_sha256=_manifest_hash(files, chunk_rows),
        files=files,
        chunks=chunk_rows,
    )
